-- Remove all demo/seed operational data. Keeps admin accounts, roles, vehicle catalog,
-- pricing configs, and platform settings so the app remains usable.

-- Child tables first (explicit list avoids touching PostGIS/tiger extension tables).
TRUNCATE TABLE
    ticket_messages,
    support_tickets,
    inbox_messages,
    incident_events,
    safety_incidents,
    reports,
    scheduled_reports,
    negotiation_rounds,
    ride_events,
    ride_disputes,
    payments,
    wallet_transactions,
    wallets,
    ratings,
    notifications,
    analytics_events,
    driver_documents,
    driver_locations,
    driver_ride_credits,
    driver_sessions,
    driver_vehicles,
    gps_anomalies,
    driver_profiles,
    customer_profiles,
    saved_locations,
    route_cache,
    otp_verifications,
    device_sessions,
    zone_demand_stats,
    rides,
    hot_zones,
    landmarks,
    ride_packages,
    users
RESTART IDENTITY CASCADE;
