-- Marks a national_id_number that was machine-generated by the
-- cmd/national-id-backfill one-off (existing drivers predating DB-1, migration
-- 080) rather than actually captured from the driver. Without this flag a
-- placeholder is indistinguishable from a real ID once written, which would
-- silently defeat the one-ID-one-account fraud guard uq_users_national_id
-- exists for (a placeholder is not evidence of anything about the person) and
-- would make it impossible to find + reconcile these rows later against the
-- real ID images already on file (driver_documents NATIONAL_ID_FRONT/BACK).
--
-- Defaults FALSE (not NOT NULL DEFAULT true) so every existing row — real ID
-- or no ID at all — is correctly "not a placeholder" without a backfill pass
-- of its own; only the national-ID backfill command sets it true, and only on
-- the rows it generates.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS national_id_placeholder BOOLEAN NOT NULL DEFAULT false;
